name: Rust

on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.rs"
      - "Cargo.lock"
      - "Cargo.toml"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "**.rs"
      - "Cargo.lock"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

# https://github.com/actions-rs/cargo
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: format
        run: cargo fmt --check --verbose

      - name: build
        run: cargo build

      - name: lint
        # exit non-zero if there are any warnings
        # https://doc.rust-lang.org/stable/clippy/usage.html
        run: cargo clippy -- -Dwarnings
